name: LambdaTest Tunnel Workflow

on: [push]

jobs:
  lambdatest-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Environment
      run: |
        docker pull lambdatest/tunnel
        docker run -d --name lambdatest-tunnel -e LT_USERNAME='shubhamr' -e LT_ACCESS_KEY=' dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh' lambdatest/tunnel:latest

   

  
